### PR TITLE
fix(button): prevent unnecessary paints of button icon

### LINKED ISSUE #19: Eliminate redundant paints of button UI
`feature::_noUser` and `feature::_unverifiedUser` both call `browser.browserAction.setIcon` twice on each invocation. And this is exacerbated by `feature::_defaultAvatar` not using the cached avatar info to short-circuit its call when possible. We should be able to fix all that with sensible caching of the last used avatar and comparing against it each time.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #19.

The main fix here, d262c0c, ensures that we only paint the button icon when it changes and we stop painting it multiple times per profile-update.

I also included two smaller, kind-of-related changes:

* In b7813f7, I tweaked the conditional code in `updateState` to be cleaner. Previously it was leading with a negative condition, which is harder for a reader to grok. But also, instead of using `else` or `return` to control the flow, it was re-asserting the negation of the earlier condition in later ones. So I flipped it round to lead with the positive condition and then use `else` for control flow.

* While testing, I noticed that some calls to `userAvatar` were being made with a `null` value for `url`. I fixed that in 732817a by flipping the conditions in `verifiedUser` so that we only make the call to `userAvatar` when `user.avatar` is set.

@vbudhram r?

### CODE REVIEW

File: src/feature.js [hunk 1]
```diff
@@ -65,59 +74,55 @@ class FxABrowserFeature {
...
+      }
+    } else {
+      this.noUser();
     }
   }
 
-  _noUser() {
-    this._defaultAvatar();
-    browser.browserAction.setIcon({ path: "icons/avatar.svg" });
+  noUser() {
```
Comment (philbooth) [inline src/feature.js]: Fwiw I ditched the leading `_` on these "private" methods to resolve a naming clash between the property `this._userAvatar` and the method `this._userAvatar()`.

File: src/feature.js [hunk 2]
```diff
@@ -65,59 +74,55 @@ class FxABrowserFeature {
...
-  _userAvatar(url) {
-    if (this._avatar && this._avatarUrl === url) {
+  userAvatar(url) {
+    if (this._avatar === USER_AVATAR && this._userAvatar === url) {
       return;
     }
 
-    this._avatarUrl = url;
+    this._avatar = USER_AVATAR;
+    this._userAvatar = url;
```
Comment (vbudhram) [inline src/feature.js]: For urls I like to put `Url` in variable name but meh.
